source 'https://github.com/CocoaPods/Specs.git'

target 'XLEasyCache_Example', :exclusive => true do
  pod "XLEasyCache", :path => "../"
end

target 'XLEasyCache_Tests', :exclusive => true do
  pod "XLEasyCache", :path => "../"

  
end
